name = "tax-loss-harvester"
main = "worker/index.ts"
compatibility_date = "2024-02-08"

routes = [
	{ pattern = "harvester.v.ibe.dev", custom_domain = true }
]



[[kv_namespaces]]
binding = "FINNHUB_CACHE"
id = "7dc672b79c45421dafcecd05b975b861"

[assets]
directory = "./dist"
binding = "ASSETS"

[env.staging]
routes = [
	{ pattern = "harvester.stage.v.ibe.dev", custom_domain = true }
]

[[env.staging.kv_namespaces]]
binding = "FINNHUB_CACHE"
id = "7dc672b79c45421dafcecd05b975b861"

[observability]
enabled = true
head_sampling_rate = 1

